# Generated by Django 3.2.13 on 2023-02-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_history_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.customuser', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
