# Generated by Django 3.2.13 on 2023-02-25 17:42

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_history_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(blank=True, upload_to='Album', verbose_name='Первое изображение')),
                ('second_image', models.ImageField(blank=True, upload_to='Album', verbose_name='Второе изображение')),
                ('third_image', models.ImageField(blank=True, upload_to='Album', verbose_name='Третье изображение')),
                ('fourth_image', models.ImageField(blank=True, upload_to='Album', verbose_name='Четвёртое изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=main.models.IntegerRangeField(default=1, verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='history',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='Изображения'),
        ),
    ]
